### ISSUE TITLE
browser support ? (es6 + promise)

### ISSUE THREAD

**Issue by orenmizr** [anywhichway/scriptswitch#1]
it does not look to support ie11, ie10. which is a common use case for script loading - adding polyfill for these broken browsers.

**Comment by anywhichway** [comment]
@orenmizr Think this is fixed in v0.1.2, along with some other older browser compatibility things. Have applied for an open source browserstack account to verify, but you might give it a shot.

**Comment by anywhichway** [comment]
@orenmizr Basic functionality now works as far back as IE 10, Safari 5.1, Firefox 8, Chrome 10. `async` and `defer` only work if the browser supports them.
